# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

variables:
 - group test_build

trigger:
- main

pool:

  vmImage: 'windows-2019'

steps:
- script: echo $(BUILDVERSION)
- task: NuGetToolInstaller@1
  inputs:
    checkLatest: true
- task: NuGetCommand@2
  inputs:
    command: 'custom'
    arguments: 'sources remove -Name VCCAPI'

- task: NuGetAuthenticate@0
  inputs:
    forceReinstallCredentialProvider: true

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
