# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

variables:
 - group: test_build

trigger:
- main

pool:

  vmImage: 'windows-2019'

steps:
- script: echo $(BUILDVERSION)
- task: NuGetToolInstaller@1
  inputs:
    checkLatest: true

#specific package for our project, should I fake it?
# - task: NuGetCommand@2
#   inputs:
#     command: 'custom'
#     arguments: 'sources remove -Name VCCAPI'

- task: NuGetAuthenticate@0
  inputs:
    forceReinstallCredentialProvider: true

- task: NodeTool@0
  inputs:
    versionSpec: '1.x'
    checkLatest: true

- task: Cake@2
  inputs:
    script: build.cake
    target: 'Default'
    arguments: '-BUILDVERSION=$(BUILDVERSION) -BUILDVCSNUMBER=$(BUILDVCSNUMBER)'
    useBuildAgentNugetExe: true
    Bootstrap: true
    Version: '0.38.5'

# - task: NuGetCommand@2
#   inputs:
#     command: 'custom'
#     arguments: 'sources remove -Name VCCAPI'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactsStagingDirectory)'
    artifact: 'TestApp'
    publishLocation: 'pipeline'